name: Build XBPS Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/void-linux/void-buildroot-glibc:latest

    steps:
      - name: Install tools
        run: |
          xbps-install -Sy xbps git tar gzip

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone void-packages
        run: |
          git clone https://github.com/void-linux/void-packages.git

      - name: Bootstrap
        run: |
          cd void-packages
          ./xbps-src binary-bootstrap

      - name: Build packages
        run: |
          cd void-packages
          ./xbps-src pkg discord

      - name: Create repo
        run: |
          mkdir -p current/x86_64

          find void-packages/hostdir/binpkgs -name "*.xbps" \
            -exec cp {} current/x86_64/ \;

          xbps-rindex -fa current/x86_64/*.xbps

      - name: Commit packages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add current/

          git commit -m "Update XBPS repo" || echo "No changes"

          git push
